services:
    api:
        image: pratigo/laravel-api:latest
        container_name: pratigo-api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            -   "8000:8000"
        networks:
            - proxy
        depends_on:
            - api-builder
        env_file:
            - ${BASEDIR}/repositories/api/.env
        environment:
            - GITLAB_API_AUTH:$GITLAB_API_AUTH
            - PHP_IDE_CONFIG:"serverName=Docker"
        entrypoint: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
        volumes:
            - ${BASEDIR}/repositories/api:/var/www/app
            - ${BASEDIR}/repositories/api/bootstrap/cache:/var/www/app/bootstrap/cache

    api-builder:
        build:
            context: ${BASEDIR}/repositories/api
            dockerfile: ${BASEDIR}/repositories/api/Dockerfile
            args:
                DB_CONNECTION: sqlite
                DB_DATABASE: ":memory:"
                NEW_RELIC_AGENT_VERSION: 10.21.0.11
                NEW_RELIC_LICENSE_KEY: ""
                NEW_RELIC_APPNAME: "dev-pratigo-api"
                APP_ENV: local
                GITLAB_API_AUTH: ${GITLAB_API_AUTH}
        image: pratigo/laravel-api:latest
        container_name: api-builder
        networks:
            - proxy
        restart: "no"
        entrypoint: ["echo", "finished"]
        depends_on:
            - db-api
