services:
    pratigo-api-dev:
        image: pratigo/laravel-api:latest
        container_name: pratigo-api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            -   "8000:8000"
        networks:
            - pratigo
        depends_on:
            - pratigo-api-builder
        env_file:
            - .env
        environment:
            - GITLAB_API_AUTH:$GITLAB_API_AUTH
            - PHP_IDE_CONFIG:"serverName=Docker"
        entrypoint: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
        volumes:
            - .:/var/www/app
            - ./bootstrap/cache:/var/www/app/bootstrap/cache

    pratigo-api-builder:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DB_CONNECTION: sqlite
                DB_DATABASE: ":memory:"
                NEW_RELIC_AGENT_VERSION: 10.21.0.11
                NEW_RELIC_LICENSE_KEY: ""
                NEW_RELIC_APPNAME: "dev-pratigo-api"
                APP_ENV: local
                GITLAB_API_AUTH: ${GITLAB_API_AUTH} #"user token"
        image: pratigo/laravel-api:latest
        container_name: pratigo-api-builder
        networks:
            - pratigo
        restart: "no"
        entrypoint: ["echo", "finished"]
        depends_on:
            - pratigo-db