services:
    socket:
        image: pratigo/websocket-server:latest
        build: 
            context: ${BASEDIR}/repositories/socket
        container_name: websocket-server
        ports:
            -   "2000:2000"
        environment:
            - PRATIGO_API=http://api:8000
        volumes:
            - ${BASEDIR}/repositories/socket:/app
        networks:
            -proxy
