networks:
  proxy:
    name: ${NETWORK}
    external: true

volumes:
  db_data:

services:
  db-api:
    extends:
      file: ${BASEDIR}/dockers/db-api.yml
      service: db-api

  api:
    extends:
      file: ${BASEDIR}/dockers/api.yml
      service: api

  api-builder:
    extends:
      file: ${BASEDIR}/dockers/api.yml
      service: api-builder
    
  gestor:
    extends:
      file: ${BASEDIR}/dockers/gestor.yml
      service: gestor

  socket:
    extends:
      file: ${BASEDIR}/dockers/socket.yml
      service: socket

