networks:
  proxy:
    name: ${NETWORK}
    external: true

services:
  db-api:
    extends:
      file: ${BASEDIR}/dockers/db-api.yml
      service: db-api

  api:
    extends:
      file: ${BASEDIR}/dockers/api.yml
      service: api
    
  gestor:
    extends:
      file: ${BASEDIR}/dockers/gestor.yml
      service: gestor

  socket:
    extends:
      file: ${BASEDIR}/dockers/socket.yml
      service: socket

