- name: Clone all Pratigo repositories
  hosts: localhost
  gather_facts: false
  vars:
    base_dir: '{{ lookup("env", "BASEDIR") }}'
    token: '{{ lookup("env", "GITLAB_TOKEN") }}'
  tasks:
    - name: api
      git:
        repo: https://{{token}}@gitlab.com/lazaro-shev/pratigo-api-laravel.git
        dest: "{{base_dir}}/repositories/api"
        version: main
        clone: yes
        update: yes
    
    - name: gestor
      git:
        repo: https://{{token}}@gitlab.com/lazaro-shev/pratigo-gestor.git
        dest: "{{base_dir}}/repositories/gestor"
        version: main
        clone: yes
        update: yes

    - name: pwa
      git:
        repo: https://{{token}}@gitlab.com/lazaro-shev/pratigo-app-pwa.git
        dest: "{{base_dir}}/repositories/pwa"
        version: main
        clone: yes
        update: yes

    - name: socket
      git:
        repo: https://gitlab.com/lazaro-shev/pratigo-socketserver.git
        dest: "{{base_dir}}/repositories/socket"
        version: main
        clone: yes
        update: yes
        